

- name: Installing zabbix agent
  hosts: all
  become: yes

  tasks:

    - name: Installing Zabbix repo
      yum: name="http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm" state=present

    - name: Installing zabbix-agent
      yum: name=zabbix-agent state=present

    - name: Change
      shell: cd /etc/ && chown -R zabbix:zabbix zabbix/

    - name: Starting zabbix-agent
      service: name=zabbix-agent state=started enabled=yes
