- name: Installing Zabbix server
  hosts: all
  become: yes

  tasks:
    - name: Installing MySQL
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - mysql
        - mysql-server
        - MySQL-python

    - name: Changing cnf file
      template: src=conf.cnf dest=/etc/

    - name: Configuring MySQL
      shell: /usr/bin/mysql_install_db --user=mysql

    - name: Starting MySQL-server
      service: name=mysqld state=started enabled=yes

    - name: Installing Zabbix repo
      yum:
        name: "http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm"
        state: present

    - name: Installing zabbix
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - zabbix 
        - zabbix-server
        - zabbix-agent 
        - zabbix-server-mysql 
        - zabbix-web-mysql

    - name: Creating database Zabbix MySQL
      mysql_db: name=zabbix encoding=utf8 collation=utf8_bin state=present

    - name: Creating user in database with creds
      mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL

    - name: Importing schema
      shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.2.14/create/schema.sql

    - name: Importing image
      shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.2.14/create/images.sql

    - name: Importing data
      shell: mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.2.14/create/data.sql

    - name: Changing zabbix.conf
      template: src=zabbix.conf dest=/etc/httpd/conf.d/

    - name: Changing config for Zabbix server
      template: src=zabbix_server.conf dest=/etc/zabbix/

    - name: Starting zabbix-server
      service: name=zabbix-server state=started enabled=yes

    - name: Starting httpd
      service: name=httpd state=started enabled=yes
